//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MoreMoreTest
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Детейл2.
    /// </summary>
    //  *** Start programmer edit section *** (Детейл2 CustomAttributes)

    //  *** End programmer edit section *** (Детейл2 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Детейл2E", new string[] {
            "А as \'А\'"})]
    public class Детейл2 : ICSSoft.STORMNET.DataObject
    {
        
        private string fА;
        
        private IIS.MoreMoreTest.Детейл1 fДетейл1;
        
        //  *** Start programmer edit section *** (Детейл2 CustomMembers)

        //  *** End programmer edit section *** (Детейл2 CustomMembers)

        
        /// <summary>
        /// А.
        /// </summary>
        //  *** Start programmer edit section *** (Детейл2.А CustomAttributes)

        //  *** End programmer edit section *** (Детейл2.А CustomAttributes)
        [StrLen(255)]
        public virtual string А
        {
            get
            {
                //  *** Start programmer edit section *** (Детейл2.А Get start)

                //  *** End programmer edit section *** (Детейл2.А Get start)
                string result = this.fА;
                //  *** Start programmer edit section *** (Детейл2.А Get end)

                //  *** End programmer edit section *** (Детейл2.А Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Детейл2.А Set start)

                //  *** End programmer edit section *** (Детейл2.А Set start)
                this.fА = value;
                //  *** Start programmer edit section *** (Детейл2.А Set end)

                //  *** End programmer edit section *** (Детейл2.А Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.MoreMoreTest.Детейл1.
        /// </summary>
        //  *** Start programmer edit section *** (Детейл2.Детейл1 CustomAttributes)

        //  *** End programmer edit section *** (Детейл2.Детейл1 CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.MoreMoreTest.Детейл1 Детейл1
        {
            get
            {
                //  *** Start programmer edit section *** (Детейл2.Детейл1 Get start)

                //  *** End programmer edit section *** (Детейл2.Детейл1 Get start)
                IIS.MoreMoreTest.Детейл1 result = this.fДетейл1;
                //  *** Start programmer edit section *** (Детейл2.Детейл1 Get end)

                //  *** End programmer edit section *** (Детейл2.Детейл1 Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Детейл2.Детейл1 Set start)

                //  *** End programmer edit section *** (Детейл2.Детейл1 Set start)
                this.fДетейл1 = value;
                //  *** Start programmer edit section *** (Детейл2.Детейл1 Set end)

                //  *** End programmer edit section *** (Детейл2.Детейл1 Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Детейл2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Детейл2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Детейл2E", typeof(IIS.MoreMoreTest.Детейл2));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Детейл2.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfДетейл2 CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfДетейл2 CustomAttributes)
    public class DetailArrayOfДетейл2 : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.MoreMoreTest.DetailArrayOfДетейл2 members)

        //  *** End programmer edit section *** (IIS.MoreMoreTest.DetailArrayOfДетейл2 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Детейл2 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Детейл2.
        /// </summary>
        public DetailArrayOfДетейл2(IIS.MoreMoreTest.Детейл1 fДетейл1) : 
                base(typeof(Детейл2), ((ICSSoft.STORMNET.DataObject)(fДетейл1)))
        {
        }
        
        public IIS.MoreMoreTest.Детейл2 this[int index]
        {
            get
            {
                return ((IIS.MoreMoreTest.Детейл2)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.MoreMoreTest.Детейл2 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
