//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MoreMoreTest
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Детейл1.
    /// </summary>
    //  *** Start programmer edit section *** (Детейл1 CustomAttributes)

    //  *** End programmer edit section *** (Детейл1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Детейл1E", new string[] {
            "А as \'А\'",
            "МастерДетейл1 as \'Мастер детейл1\'",
            "МастерДетейл1.А as \'А\'"}, Hidden=new string[] {
            "МастерДетейл1.А"})]
    [AssociatedDetailViewAttribute("Детейл1E", "Детейл2", "Детейл2E", true, "", "Детейл2", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("Детейл1E", "МастерДетейл1", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "А")]
    public class Детейл1 : ICSSoft.STORMNET.DataObject
    {
        
        private string fА;
        
        private IIS.MoreMoreTest.МастерДетейл1 fМастерДетейл1;
        
        private IIS.MoreMoreTest.DetailArrayOfДетейл2 fДетейл2;
        
        private IIS.MoreMoreTest.Агрегатор fАгрегатор;
        
        //  *** Start programmer edit section *** (Детейл1 CustomMembers)

        //  *** End programmer edit section *** (Детейл1 CustomMembers)

        
        /// <summary>
        /// А.
        /// </summary>
        //  *** Start programmer edit section *** (Детейл1.А CustomAttributes)

        //  *** End programmer edit section *** (Детейл1.А CustomAttributes)
        [StrLen(255)]
        public virtual string А
        {
            get
            {
                //  *** Start programmer edit section *** (Детейл1.А Get start)

                //  *** End programmer edit section *** (Детейл1.А Get start)
                string result = this.fА;
                //  *** Start programmer edit section *** (Детейл1.А Get end)

                //  *** End programmer edit section *** (Детейл1.А Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Детейл1.А Set start)

                //  *** End programmer edit section *** (Детейл1.А Set start)
                this.fА = value;
                //  *** Start programmer edit section *** (Детейл1.А Set end)

                //  *** End programmer edit section *** (Детейл1.А Set end)
            }
        }
        
        /// <summary>
        /// Детейл1.
        /// </summary>
        //  *** Start programmer edit section *** (Детейл1.МастерДетейл1 CustomAttributes)

        //  *** End programmer edit section *** (Детейл1.МастерДетейл1 CustomAttributes)
        [NotNull()]
        public virtual IIS.MoreMoreTest.МастерДетейл1 МастерДетейл1
        {
            get
            {
                //  *** Start programmer edit section *** (Детейл1.МастерДетейл1 Get start)

                //  *** End programmer edit section *** (Детейл1.МастерДетейл1 Get start)
                IIS.MoreMoreTest.МастерДетейл1 result = this.fМастерДетейл1;
                //  *** Start programmer edit section *** (Детейл1.МастерДетейл1 Get end)

                //  *** End programmer edit section *** (Детейл1.МастерДетейл1 Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Детейл1.МастерДетейл1 Set start)

                //  *** End programmer edit section *** (Детейл1.МастерДетейл1 Set start)
                this.fМастерДетейл1 = value;
                //  *** Start programmer edit section *** (Детейл1.МастерДетейл1 Set end)

                //  *** End programmer edit section *** (Детейл1.МастерДетейл1 Set end)
            }
        }
        
        /// <summary>
        /// Детейл1.
        /// </summary>
        //  *** Start programmer edit section *** (Детейл1.Детейл2 CustomAttributes)

        //  *** End programmer edit section *** (Детейл1.Детейл2 CustomAttributes)
        public virtual IIS.MoreMoreTest.DetailArrayOfДетейл2 Детейл2
        {
            get
            {
                //  *** Start programmer edit section *** (Детейл1.Детейл2 Get start)

                //  *** End programmer edit section *** (Детейл1.Детейл2 Get start)
                if ((this.fДетейл2 == null))
                {
                    this.fДетейл2 = new IIS.MoreMoreTest.DetailArrayOfДетейл2(this);
                }
                IIS.MoreMoreTest.DetailArrayOfДетейл2 result = this.fДетейл2;
                //  *** Start programmer edit section *** (Детейл1.Детейл2 Get end)

                //  *** End programmer edit section *** (Детейл1.Детейл2 Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Детейл1.Детейл2 Set start)

                //  *** End programmer edit section *** (Детейл1.Детейл2 Set start)
                this.fДетейл2 = value;
                //  *** Start programmer edit section *** (Детейл1.Детейл2 Set end)

                //  *** End programmer edit section *** (Детейл1.Детейл2 Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.MoreMoreTest.Агрегатор.
        /// </summary>
        //  *** Start programmer edit section *** (Детейл1.Агрегатор CustomAttributes)

        //  *** End programmer edit section *** (Детейл1.Агрегатор CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.MoreMoreTest.Агрегатор Агрегатор
        {
            get
            {
                //  *** Start programmer edit section *** (Детейл1.Агрегатор Get start)

                //  *** End programmer edit section *** (Детейл1.Агрегатор Get start)
                IIS.MoreMoreTest.Агрегатор result = this.fАгрегатор;
                //  *** Start programmer edit section *** (Детейл1.Агрегатор Get end)

                //  *** End programmer edit section *** (Детейл1.Агрегатор Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Детейл1.Агрегатор Set start)

                //  *** End programmer edit section *** (Детейл1.Агрегатор Set start)
                this.fАгрегатор = value;
                //  *** Start programmer edit section *** (Детейл1.Агрегатор Set end)

                //  *** End programmer edit section *** (Детейл1.Агрегатор Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Детейл1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Детейл1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Детейл1E", typeof(IIS.MoreMoreTest.Детейл1));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Детейл1.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfДетейл1 CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfДетейл1 CustomAttributes)
    public class DetailArrayOfДетейл1 : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.MoreMoreTest.DetailArrayOfДетейл1 members)

        //  *** End programmer edit section *** (IIS.MoreMoreTest.DetailArrayOfДетейл1 members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Детейл1 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Детейл1.
        /// </summary>
        public DetailArrayOfДетейл1(IIS.MoreMoreTest.Агрегатор fАгрегатор) : 
                base(typeof(Детейл1), ((ICSSoft.STORMNET.DataObject)(fАгрегатор)))
        {
        }
        
        public IIS.MoreMoreTest.Детейл1 this[int index]
        {
            get
            {
                return ((IIS.MoreMoreTest.Детейл1)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.MoreMoreTest.Детейл1 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
