//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MoreMoreTest
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Мастер агрегатор.
    /// </summary>
    //  *** Start programmer edit section *** (МастерАгрегат CustomAttributes)

    //  *** End programmer edit section *** (МастерАгрегат CustomAttributes)
    [AutoAltered()]
    [Caption("Мастер агрегатор")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МастерАгрегаторE", new string[] {
            "А as \'А\'"})]
    [View("МастерАгрегаторL", new string[] {
            "А as \'А\'"})]
    public class МастерАгрегат : ICSSoft.STORMNET.DataObject
    {
        
        private string fА;
        
        //  *** Start programmer edit section *** (МастерАгрегат CustomMembers)

        //  *** End programmer edit section *** (МастерАгрегат CustomMembers)

        
        /// <summary>
        /// А.
        /// </summary>
        //  *** Start programmer edit section *** (МастерАгрегат.А CustomAttributes)

        //  *** End programmer edit section *** (МастерАгрегат.А CustomAttributes)
        [StrLen(255)]
        public virtual string А
        {
            get
            {
                //  *** Start programmer edit section *** (МастерАгрегат.А Get start)

                //  *** End programmer edit section *** (МастерАгрегат.А Get start)
                string result = this.fА;
                //  *** Start programmer edit section *** (МастерАгрегат.А Get end)

                //  *** End programmer edit section *** (МастерАгрегат.А Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (МастерАгрегат.А Set start)

                //  *** End programmer edit section *** (МастерАгрегат.А Set start)
                this.fА = value;
                //  *** Start programmer edit section *** (МастерАгрегат.А Set end)

                //  *** End programmer edit section *** (МастерАгрегат.А Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МастерАгрегаторE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерАгрегаторE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерАгрегаторE", typeof(IIS.MoreMoreTest.МастерАгрегат));
                }
            }
            
            /// <summary>
            /// "МастерАгрегаторL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерАгрегаторL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерАгрегаторL", typeof(IIS.MoreMoreTest.МастерАгрегат));
                }
            }
        }
    }
}
