//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.MoreMoreTest
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Мастер детейл1.
    /// </summary>
    //  *** Start programmer edit section *** (МастерДетейл1 CustomAttributes)

    //  *** End programmer edit section *** (МастерДетейл1 CustomAttributes)
    [AutoAltered()]
    [Caption("Мастер детейл1")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МастерДетейл1E", new string[] {
            "А as \'А\'"})]
    [View("МастерДетейл1L", new string[] {
            "А as \'А\'"})]
    public class МастерДетейл1 : ICSSoft.STORMNET.DataObject
    {
        
        private string fА;
        
        //  *** Start programmer edit section *** (МастерДетейл1 CustomMembers)

        //  *** End programmer edit section *** (МастерДетейл1 CustomMembers)

        
        /// <summary>
        /// А.
        /// </summary>
        //  *** Start programmer edit section *** (МастерДетейл1.А CustomAttributes)

        //  *** End programmer edit section *** (МастерДетейл1.А CustomAttributes)
        [StrLen(255)]
        public virtual string А
        {
            get
            {
                //  *** Start programmer edit section *** (МастерДетейл1.А Get start)

                //  *** End programmer edit section *** (МастерДетейл1.А Get start)
                string result = this.fА;
                //  *** Start programmer edit section *** (МастерДетейл1.А Get end)

                //  *** End programmer edit section *** (МастерДетейл1.А Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (МастерДетейл1.А Set start)

                //  *** End programmer edit section *** (МастерДетейл1.А Set start)
                this.fА = value;
                //  *** Start programmer edit section *** (МастерДетейл1.А Set end)

                //  *** End programmer edit section *** (МастерДетейл1.А Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МастерДетейл1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерДетейл1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерДетейл1E", typeof(IIS.MoreMoreTest.МастерДетейл1));
                }
            }
            
            /// <summary>
            /// "МастерДетейл1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МастерДетейл1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МастерДетейл1L", typeof(IIS.MoreMoreTest.МастерДетейл1));
                }
            }
        }
    }
}
